# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 80
  tables: false
  code_blocks: false

# MD033/no-inline-html : Inline HTML : https://github.com/DavidAnson/markdownlint/blob/v0.35.0/doc/md033.md
MD033:
  # Allowed elements
  allowed_elements: ["br"]
